spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/card_management
    username: postgres
    password: 161092
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/migration/master.xml
    enabled: true

app:
  encryption:
    key: your-strong-encryption-key-32-chars # Должен быть 32 символа для AES-256
  jwt:
    secret: your-secret-key-here-1234567890
    expiration-ms: 86400000

logging:
  level:
    org.springframework.security: DEBUG
    com.example.cardmanagement: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha