spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/card_management
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/migration/master.xml
    enabled: true

app:
  jwt:
    secret: your-secret-key-here-1234567890
    expiration-ms: 86400000 # 24 hours

logging:
  level:
    org.springframework.security: DEBUG
    com.example.cardmanagement: DEBUG